version: "3.8"

services:
  app:
    image: ghcr.io/your-username/your-repo:latest
    container_name: lims-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./uploads:/app/public/uploads
    networks:
      - lims-network

  # 可选：添加 Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: lims-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - lims-network

networks:
  lims-network:
    driver: bridge
